# Generated by Django 6.0.3 on 2026-03-12 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("berths", "0001_initial"),
        ("clients", "0001_initial"),
        ("ships", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BerthingRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cargo_type", models.CharField(max_length=100)),
                (
                    "cargo_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("eta", models.DateTimeField()),
                ("operation_type", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="WAITING",
                        max_length=20,
                    ),
                ),
                (
                    "bypass",
                    models.BooleanField(
                        default=False, help_text="True means the ship left the queue."
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="berthing_requests",
                        to="clients.client",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="berthing_requests",
                        to="ships.ship",
                    ),
                ),
            ],
            options={
                "ordering": ["eta"],
            },
        ),
        migrations.CreateModel(
            name="Lineup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("position", models.PositiveIntegerField()),
                (
                    "berth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineups",
                        to="berths.berth",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineups",
                        to="ships.ship",
                    ),
                ),
            ],
            options={
                "ordering": ["berth", "position"],
            },
        ),
        migrations.CreateModel(
            name="OperationAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RAIN", "Rain"),
                            ("MAINTENANCE", "Maintenance"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("hours", models.DecimalField(decimal_places=2, max_digits=6)),
                ("reason", models.TextField(blank=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="lineup.berthingrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shifting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time", models.DateTimeField()),
                (
                    "from_berth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shiftings_from",
                        to="berths.berth",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shiftings",
                        to="ships.ship",
                    ),
                ),
                (
                    "to_berth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shiftings_to",
                        to="berths.berth",
                    ),
                ),
            ],
            options={
                "ordering": ["time"],
            },
        ),
    ]
