# Generated by Django 6.0.3 on 2026-03-12 21:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("berths", "0005_berth_name_berthneighbor_min_distance_and_more"),
        ("lineup", "0002_extend_lineup_models"),
        ("ships", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DELAYED_SHIP", "Navio Atrasado"),
                            ("IDLE_BERTH", "Berço Ocioso"),
                            ("BERTH_CONFLICT", "Conflito de Berço"),
                            ("RULE_VIOLATION", "Violação de Regra"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Informação"),
                            ("WARNING", "Atenção"),
                            ("CRITICAL", "Crítico"),
                        ],
                        default="WARNING",
                        max_length=10,
                    ),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "berth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="berths.berth",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="ships.ship",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ATRACACAO", "Atracação"),
                            ("DESATRACACAO", "Desatracação"),
                            ("SHIFTING", "Shifting"),
                            ("CHUVA", "Chuva"),
                            ("PARADA", "Parada de Operação"),
                            ("ETA_UPDATE", "Atualização de ETA"),
                            ("MANUAL_OVERRIDE", "Ajuste Manual"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "berth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="port_events",
                        to="berths.berth",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="port_events",
                        to="ships.ship",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ShipETAUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("old_eta", models.DateTimeField()),
                ("new_eta", models.DateTimeField()),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("AIS", "AIS"),
                            ("MANUAL", "Manual"),
                            ("AGENT", "Agente"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "berthing_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eta_updates",
                        to="lineup.berthingrequest",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eta_updates",
                        to="ships.ship",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
