# Generated by Django 6.0.3 on 2026-03-12 17:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=100)),
                ("timezone", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
