# Generated by Django 6.0.3 on 2026-03-12 17:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "loa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Length Overall in meters",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "beam",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Ship beam (width) in meters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "dwt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Deadweight tonnage",
                        max_digits=12,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
