# Generated by Django 6.0.3 on 2026-03-12 17:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher value means higher scheduling priority (e.g. Suzano, Tegram, Vale)",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "name"],
            },
        ),
    ]
