# Generated by Django 6.0.3 on 2026-03-12 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Berth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Berth length in meters",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_loa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum Length Overall accepted (meters)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "depth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Water depth at berth in meters",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="berths",
                        to="ports.port",
                    ),
                ),
            ],
            options={
                "ordering": ["port", "number"],
            },
        ),
    ]
