# Generated by Django 6.0.3 on 2026-03-12 17:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("berths", "0001_initial"),
        ("cargo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rule_type", models.CharField(max_length=50)),
                ("target", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["rule_type", "target"],
            },
        ),
        migrations.AddField(
            model_name="berth",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="berth",
            name="position_end",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cais end coordinate in meters",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="berth",
            name="position_start",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cais start coordinate in meters",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BerthCargo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "max_prancha",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                (
                    "berth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargo_configs",
                        to="berths.berth",
                    ),
                ),
                (
                    "cargo_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="berth_configs",
                        to="cargo.cargotype",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority"],
                "unique_together": {("berth", "cargo_type")},
            },
        ),
    ]
