# Generated by Django 6.0.3 on 2026-03-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("berths", "0003_berthneighbor"),
    ]

    operations = [
        migrations.AddField(
            model_name="berth",
            name="crane_capacity_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Capacidade mínima do guindaste em toneladas",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="berth",
            name="default_ship_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tipo de navio padrão (ex: Bulk Carrier, Tanker)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="berth",
            name="max_air_draft",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Calado aéreo máximo em metros",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="berth",
            name="max_beam",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Boca máxima aceita em metros",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="berth",
            name="max_draft",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Calado máximo de entrada/saída em metros",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="berth",
            name="max_dwt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="DWT máximo em toneladas",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="berth",
            name="max_ship_age",
            field=models.PositiveIntegerField(
                blank=True, help_text="Idade máxima do navio em anos", null=True
            ),
        ),
    ]
