# Generated by Django 6.0.3 on 2026-03-12 21:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("berths", "0004_berth_crane_capacity_min_berth_default_ship_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="berth",
            name="name",
            field=models.CharField(
                blank=True, default="", help_text="Nome do berço", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="berthneighbor",
            name="min_distance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Distância mínima em metros entre os navios",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="berthneighbor",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="berthneighbor",
            name="restriction_type",
            field=models.CharField(
                choices=[
                    ("NONE", "Nenhuma"),
                    ("DISTANCE", "Distância Mínima"),
                    ("FORBIDDEN", "Proibido"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
    ]
