# Generated by Django 6.0.3 on 2026-03-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("berths", "0005_berth_name_berthneighbor_min_distance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="berth",
            name="status",
            field=models.CharField(
                choices=[
                    ("ATIVO", "Ativo"),
                    ("INATIVO", "Inativo"),
                    ("OCIOSO", "Ocioso"),
                    ("MANUTENCAO", "Em Manutenção"),
                ],
                default="ATIVO",
                help_text="Status operacional do berço",
                max_length=20,
            ),
        ),
    ]
