# Generated by Django 6.0.3 on 2026-03-12 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CargoType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("solid_bulk", "Granel Sólido"),
                            ("liquid_bulk", "Granel Líquido"),
                            ("general_cargo", "Carga Geral"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "default_prancha",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
